[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyfun"
version = "0.1.0"
readme = "README.md"
license = { file = "LICENSE.md" }

[tool.setuptools.packages.find]
where = ["src"]